<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "gefahrenatlas"
 *
 * Auto generated by Extension Builder 2020-02-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Gefahrenatlas',
    'description' => 'Eintragen von Gefahrenstellen im Straßenverkehr',
    'category' => 'plugin',
    'author' => 'Matthias Hueber, Hubertus Golf',
    'author_email' => 'mhueber@freenet.de, technik@radentscheid-nuernberg.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
